apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeharbor.fullname" . }}-api
  labels:
    {{- include "homeharbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "homeharbor.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "homeharbor.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "homeharbor.fullname" . }}-config
            - secretRef:
                name: {{ include "homeharbor.fullname" . }}-secrets
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "homeharbor.fullname" . }}-pg-app
                  key: uri
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.storage.bucketName }}
                  key: BUCKET_NAME
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.bucketName }}
                  key: AWS_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.bucketName }}
                  key: AWS_SECRET_ACCESS_KEY
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
