/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AnomalyReportsRouteImport } from './routes/anomaly-reports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as DevicesIdRouteImport } from './routes/devices.$id'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyReportsRoute = AnomalyReportsRouteImport.update({
  id: '/anomaly-reports',
  path: '/anomaly-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const DevicesIdRoute = DevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomaly-reports': typeof AnomalyReportsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/work-orders': typeof WorkOrdersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomaly-reports': typeof AnomalyReportsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/work-orders': typeof WorkOrdersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomaly-reports': typeof AnomalyReportsRoute
  '/devices': typeof DevicesRouteWithChildren
  '/events': typeof EventsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/work-orders': typeof WorkOrdersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/properties/$id': typeof PropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomaly-reports'
    | '/devices'
    | '/events'
    | '/properties'
    | '/reservations'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/work-orders'
    | '/devices/$id'
    | '/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomaly-reports'
    | '/devices'
    | '/events'
    | '/properties'
    | '/reservations'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/work-orders'
    | '/devices/$id'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/anomaly-reports'
    | '/devices'
    | '/events'
    | '/properties'
    | '/reservations'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/work-orders'
    | '/devices/$id'
    | '/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomalyReportsRoute: typeof AnomalyReportsRoute
  DevicesRoute: typeof DevicesRouteWithChildren
  EventsRoute: typeof EventsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  ReservationsRoute: typeof ReservationsRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UsersRoute: typeof UsersRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-reports': {
      id: '/anomaly-reports'
      path: '/anomaly-reports'
      fullPath: '/anomaly-reports'
      preLoaderRoute: typeof AnomalyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/devices/$id': {
      id: '/devices/$id'
      path: '/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof DevicesIdRouteImport
      parentRoute: typeof DevicesRoute
    }
  }
}

interface DevicesRouteChildren {
  DevicesIdRoute: typeof DevicesIdRoute
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesIdRoute: DevicesIdRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomalyReportsRoute: AnomalyReportsRoute,
  DevicesRoute: DevicesRouteWithChildren,
  EventsRoute: EventsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  ReservationsRoute: ReservationsRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UsersRoute: UsersRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
